include ../include_top.mk

MKLROOT = /opt/intel/oneapi/mkl/latest/

# calls:
INCLUDES   = ${INCLUDES_COMMON} -I../../ext/tinyobjloader -I../../ext/ -I/usr/local/include -I${MKLROOT}/include
#CFLAGS     = ${CFLAGS_COMMON} ${INCLUDES}
CFLAGS     = ${CFLAGS_COMMON} ${INCLUDES} -DNDEBUG -DEIGEN_USE_MKL_ALL
LDFLAGS    = ${LDFLAGS_COMMON} -L/opt/intel/oneapi/compiler/latest/mac/compiler/lib ${MKLROOT}/lib/libmkl_intel_lp64.a ${MKLROOT}/lib/libmkl_intel_thread.a ${MKLROOT}/lib/libmkl_core.a -liomp5 -lpthread -lm -ldl
#LDFLAGS    = ${LDFLAGS_COMMON} -L${MKLROOT}/lib -Wl,-rpath,${MKLROOT}/lib -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lpthread -lm -ldl

MAIN = simulateStrands.cpp
SOURCES    = ../../ext/glvu/glvu.cpp \
						 ../../src/util/MATRIX_UTIL.cpp \
						 ../../src/util/COLLISION_UTIL.cpp \
						 ../../src/util/FILE_IO.cpp \
						 ../../src/util/TIMER.cpp \
						 ../../src/util/DRAW_GL.cpp \
						 ../../src/util/PCG.cpp \
						 ../../src/util/DIAGONAL.cpp \
						 ../../src/util/BLOCK_SPARSE_MATRIX3.cpp \
						 ../../src/util/BLOCK_DIAGONAL_MATRIX3.cpp \
						 ../../src/Timestepper/Volume/BACKWARD_EULER_VELOCITY.cpp \
						 ../../src/Timestepper/Volume/BACKWARD_EULER_POSITION.cpp \
						 ../../src/Timestepper/Volume/TIMESTEPPER.cpp \
						 ../../src/Timestepper/Volume/BDF_1.cpp \
						 ../../src/Timestepper/Volume/BDF_2.cpp \
						 ../../src/Timestepper/Volume/NEWMARK.cpp \
						 ../../src/Timestepper/Volume/QUASISTATIC.cpp \
						 ../../src/Timestepper/Strand/TIMESTEPPER.cpp \
						 ../../src/Geometry/LINE_INTERSECT.cpp \
						 ../../src/Geometry/CAPSULE.cpp \
						 ../../src/Geometry/CYLINDER.cpp \
						 ../../src/Geometry/CUBE.cpp \
						 ../../src/Geometry/SPHERE.cpp \
						 ../../src/Geometry/AABB_TREE.cpp \
						 ../../src/Geometry/TRIANGLE_MESH.cpp \
						 ../../src/Geometry/TET_MESH.cpp \
						 ../../src/Geometry/TET_MESH_FASTER.cpp \
						 ../../src/Damping/Volume/ARAP_DAMPING.cpp \
						 ../../src/Damping/Volume/GREEN_DAMPING.cpp \
						 ../../src/Damping/Volume/EBERLE_DAMPING.cpp \
						 ../../src/Damping/Volume/EDGE_DAMPING.cpp \
						 ../../src/Hyperelastic/Volume/EDGE_COLLISION.cpp \
						 ../../src/Hyperelastic/Volume/EDGE_SQRT_COLLISION.cpp \
						 ../../src/Hyperelastic/Volume/EDGE_HYBRID_COLLISION.cpp \
						 ../../src/Hyperelastic/Volume/MCADAMS_COLLISION.cpp \
						 ../../src/Hyperelastic/Volume/MU_LINEAR_FILTER.cpp \
						 ../../src/Hyperelastic/Volume/MU_CUBIC_FILTER.cpp \
						 ../../src/Hyperelastic/Volume/VERTEX_FACE_COLLISION.cpp \
						 ../../src/Hyperelastic/Volume/VERTEX_FACE_SQRT_COLLISION.cpp \
						 ../../src/Hyperelastic/Volume/ANISOTROPIC_ARAP.cpp \
						 ../../src/Hyperelastic/Volume/ANISOTROPIC_STVK.cpp \
						 ../../src/Hyperelastic/Volume/ANISOTROPIC_FUNG.cpp \
						 ../../src/Hyperelastic/Volume/ANISOTROPIC_DIRICHLET.cpp \
						 ../../src/Hyperelastic/Volume/STVK.cpp \
						 ../../src/Hyperelastic/Volume/SNH.cpp \
						 ../../src/Hyperelastic/Volume/LINEAR.cpp \
						 ../../src/Hyperelastic/Volume/ARAP.cpp \
						 ../../src/Hyperelastic/Volume/HYPERELASTIC.cpp \
						 ../../src/Hyperelastic/Strand/QUADRATIC_STRETCHING.cpp \
						 ../../src/Hyperelastic/Strand/QUADRATIC_BENDING.cpp \
						 ../../src/Hyperelastic/Strand/QUADRATIC_UNIT_BENDING.cpp \
						 ../../src/Hyperelastic/Strand/BERGOU_2010.cpp \
						 ../../src/Hyperelastic/Strand/ISOTROPIC_THETA.cpp \
						 ../../src/Geometry/STRAND_MESH.cpp \
						 ../../src/Geometry/STRAND_MESH_FASTER.cpp

include ../include_bottom.mk
